name: Release

on:
  pull_request:
    branches:
      - '*'
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Update Version
        run: ./mvnw versions:set -DnewVersion=2.10.1
      - name: Release
        run: ./mvnw -Dmaven.test.failure.ignore=true clean verify --no-transfer-progress
      - name: Release
        run: ./mvnw -Dmaven.test.skip=true deploy --no-transfer-progress
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
